import { NextRequest, NextResponse } from 'next/server';

// Simple PDF generation without external libraries
// This creates a basic PDF with text content
function generatePDF(review: any): Buffer {
  const findings = review.findings || [];
  const riskScore = review.riskScore || {};
  
  // Create PDF content as plain text (we'll wrap it in minimal PDF structure)
  let content = `ReleaseGuard AI - Security Review Report
${'='.repeat(60)}

Review ID: ${review.id}
Repository: ${review.repository || 'N/A'}
PR Number: ${review.prNumber ? `#${review.prNumber}` : 'N/A'}
Title: ${review.title || 'Code Review'}
Analysis Date: ${new Date(review.createdAt).toLocaleString()}

${'='.repeat(60)}
RISK ASSESSMENT
${'='.repeat(60)}

Overall Risk Score: ${riskScore.totalScore}/100
Release Status: ${riskScore.releaseStatus?.toUpperCase() || 'UNKNOWN'}
Recommendation: ${riskScore.releaseStatus === 'critical' ? 'DO NOT RELEASE - Critical issues must be fixed' : 
                 riskScore.releaseStatus === 'high' ? 'RELEASE WITH CAUTION - Review all findings' :
                 riskScore.releaseStatus === 'moderate' ? 'REVIEW RECOMMENDED - Address medium priority issues' :
                 'SAFE TO RELEASE - No critical issues found'}

Category Scores:
  • Security: ${riskScore.categoryScores?.security || 0}%
  • Bugs: ${riskScore.categoryScores?.bug || 0}%
  • Performance: ${riskScore.categoryScores?.performance || 0}%
  • Maintainability: ${riskScore.categoryScores?.maintainability || 0}%

${'='.repeat(60)}
FINDINGS SUMMARY
${'='.repeat(60)}

Total Findings: ${findings.length}
  • Critical: ${findings.filter((f: any) => f.severity === 'critical').length}
  • High: ${findings.filter((f: any) => f.severity === 'high').length}
  • Medium: ${findings.filter((f: any) => f.severity === 'medium').length}
  • Low: ${findings.filter((f: any) => f.severity === 'low').length}

`;

  // Add Top 3 Must-Fix Issues
  if (riskScore.topIssues && riskScore.topIssues.length > 0) {
    content += `${'='.repeat(60)}
TOP 3 MUST-FIX ISSUES
${'='.repeat(60)}

`;
    riskScore.topIssues.forEach((issue: any, index: number) => {
      content += `${index + 1}. [${issue.severity.toUpperCase()}] ${issue.title}
   Location: ${issue.file}:${issue.line}
   Certainty: ${issue.certainty.toUpperCase()}
   Confidence: ${Math.round(issue.confidence * 100)}%
   
`;
    });
  }

  // Add detailed findings
  content += `${'='.repeat(60)}
DETAILED FINDINGS
${'='.repeat(60)}

`;

  findings.forEach((finding: any, index: number) => {
    content += `
${'-'.repeat(60)}
FINDING #${index + 1}
${'-'.repeat(60)}

Title: ${finding.title}
Severity: ${finding.severity.toUpperCase()}
Category: ${finding.category}
Certainty: ${finding.certainty.toUpperCase()}
Confidence: ${Math.round(finding.confidence * 100)}%
Location: ${finding.file}:${finding.lineStart}-${finding.lineEnd}

Description:
${finding.explanation}

Evidence:
${finding.evidence}

${finding.impact ? `Impact:
${finding.impact}

` : ''}${finding.suggestedFix ? `Suggested Fix:
${finding.suggestedFix}

` : ''}`;
  });

  // Add footer
  content += `

${'='.repeat(60)}
REPORT GENERATED BY RELEASEGUARD AI
${'='.repeat(60)}

This automated security review was generated by ReleaseGuard AI.
For questions or support, visit https://releaseguard.ai

Generated: ${new Date().toISOString()}
Report Version: 1.0
`;

  // Create a basic PDF structure
  // Note: This is a simplified PDF - for production, use a proper PDF library
  let pdfContent = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj
3 0 obj
<<
/Type /Page
/Parent 2 0 R
/Resources <<
/Font <<
/F1 <<
/Type /Font
/Subtype /Type1
/BaseFont /Courier
>>
>>
>>
/MediaBox [0 0 612 792]
/Contents 4 0 R
>>
endobj
4 0 obj
<<
/Length ${content.length + 200}
>>
stream
BT
/F1 10 Tf
50 742 Td
15 TL
`;

  // Split content into lines and add to PDF
  const lines = content.split('\n');
  let pdfLines = '';
  lines.forEach((line, index) => {
    // Escape special characters
    const escapedLine = line.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
    pdfLines += `(${escapedLine.substring(0, 90)}) Tj T*\n`;
  });

  pdfContent += pdfLines;
  pdfContent += `ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000317 00000 n 
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
${pdfContent.length + 400}
%%EOF`;

  return Buffer.from(pdfContent, 'utf-8');
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: reviewId } = await params;

    // Fetch review data from global storage
    if (!global.demoReviews) {
      return NextResponse.json(
        { error: 'No reviews found' },
        { status: 404 }
      );
    }

    const review = global.demoReviews.get(reviewId);

    if (!review) {
      return NextResponse.json(
        { error: 'Review not found' },
        { status: 404 }
      );
    }

    // Generate PDF
    const pdfBuffer = generatePDF(review);

    // Create filename
    const filename = `releaseguard-review-${reviewId}-${Date.now()}.pdf`;

    // Return PDF with appropriate headers
    return new NextResponse(pdfBuffer as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': pdfBuffer.length.toString(),
      },
    });
  } catch (error: any) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF', details: error.message },
      { status: 500 }
    );
  }
}
